
# Singular Value Decomposition (SVD)

## Contents
- Singular Value Decomposition (SVD)
- Definisi Matematis
- Interpretasi SVD
- Kesimpulan



## Singular Value Decomposition (SVD)

Singular Value Decomposition (SVD) adalah teknik faktorisasi matriks untuk menguraikan sebuah matriks menjadi tiga matriks lainnya sehingga dapat mengungkapkan aspek penting dari struktur matriks aslinya.

### Aplikasi SVD
- Pemrosesan sinyal (Signal Processing)
- Kompresi gambar (Image Compression)
- Reduksi dimensi pada Machine Learning
- Sistem rekomendasi
- Analisis data

Materi ini mengasumsikan bahwa pembaca memiliki pengetahuan dasar aljabar linear, khususnya mengenai:
- Norma vektor dan matriks
- Rank matriks
- Dekomposisi eigen
- Vektor ortonormal
- Proyeksi linear



## Definisi Matematis

Dekomposisi nilai singular (Singular Value Decomposition) dari suatu matriks riil berukuran $m \times n$ dinyatakan sebagai:

$$
A = U \Sigma V^T
$$

dengan:

### 1. Matriks U

Matriks ortogonal berukuran $m \times m$

$$
U^T U = U U^T = I
$$

Kolom-kolomnya disebut **left singular vectors**.

### 2. Matriks Σ (Sigma)

Matriks diagonal berukuran $m \times n$

$$
\Sigma =
\begin{bmatrix}
\sigma_1 & 0 & \cdots & 0\\
0 & \sigma_2 & \cdots & 0\\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & \sigma_r
\end{bmatrix}
$$

dengan:

$$
\sigma_1 \ge \sigma_2 \ge \cdots \ge \sigma_r \ge 0
$$

Nilai-nilai tersebut disebut **singular values**.



## Interpretasi SVD

### 3. Matriks $V^T$

Transpose dari matriks ortogonal $V$ berukuran $n \times n$

$$
V^T V = V V^T = I
$$

Kolom-kolom matriks $V$ disebut **right singular vectors**.

SVD memecah transformasi matriks menjadi tiga tahap:

1. $V^T$ melakukan rotasi atau refleksi data.
2. $\Sigma$ melakukan scaling.
3. $U$ melakukan rotasi atau refleksi kembali.

Dengan demikian:

$$
A = U\Sigma V^T
$$

menunjukkan bahwa matriks asli dapat direkonstruksi dari ketiga komponen tersebut.


In [2]:

import numpy as np

A = np.array([
    [1, 1, 0],
    [2, 1, 1],
    [1, 0, 3]
])

# Singular Value Decomposition
U, S, VT = np.linalg.svd(A)

print("Matrix U:")
print(U)

print("\nSingular Values:")
print(S)

print("\nMatrix V^T:")
print(VT)

# Ubah S menjadi matriks diagonal Sigma
Sigma = np.diag(S)

print("\nMatrix Sigma:")
print(Sigma)

# Rekonstruksi matriks A
hasil = U @ Sigma @ VT

print("\nHasil U @ Sigma @ V^T:")
print(np.round(hasil, 10))


Matrix U:
[[-0.21132487 -0.57735027 -0.78867513]
 [-0.57735027 -0.57735027  0.57735027]
 [-0.78867513  0.57735027 -0.21132487]]

Singular Values:
[3.73205081 2.         0.26794919]

Matrix V^T:
[[-0.57735027 -0.21132487 -0.78867513]
 [-0.57735027 -0.57735027  0.57735027]
 [ 0.57735027 -0.78867513 -0.21132487]]

Matrix Sigma:
[[3.73205081 0.         0.        ]
 [0.         2.         0.        ]
 [0.         0.         0.26794919]]

Hasil U @ Sigma @ V^T:
[[ 1.  1.  0.]
 [ 2.  1.  1.]
 [ 1. -0.  3.]]



## Kesimpulan

Singular Value Decomposition (SVD) adalah metode penting dalam aljabar linear yang menguraikan suatu matriks menjadi:

$$
A = U\Sigma V^T
$$

dengan:

- $U$ berisi vektor singular kiri
- $\Sigma$ berisi nilai singular
- $V^T$ berisi vektor singular kanan

SVD banyak digunakan pada:
- Kompresi data
- Analisis citra
- Reduksi dimensi
- Machine Learning
- Sistem rekomendasi
